---

- apt: update_cache=yes
       cache_valid_time=3600

- apt: pkg={{ item }}
       state=installed
  tags: dependencies
  with_items:
    - git
    - python-pip
    - python-virtualenv
    - virtualenvwrapper

- pip: requirements={{ app_path }}/requirements.txt
       virtualenv={{ app_virtualenv }}
  tags: dependencies
